"""Major Florida cities for statewide HVAC lead search."""

FLORIDA_CITIES = [
    # Northeast / Jacksonville area
    "Jacksonville, FL",
    "Fernandina Beach, FL",
    "Orange Park, FL",
    "Middleburg, FL",
    "St. Augustine, FL",
    "Palatka, FL",
    "Lake City, FL",
    "Live Oak, FL",
    # Panhandle
    "Pensacola, FL",
    "Panama City, FL",
    "Panama City Beach, FL",
    "Destin, FL",
    "Fort Walton Beach, FL",
    "Crestview, FL",
    "Niceville, FL",
    "Marianna, FL",
    "Quincy, FL",
    "Perry, FL",
    # Tallahassee / North Central
    "Tallahassee, FL",
    "Gainesville, FL",
    "Ocala, FL",
    # Tampa Bay
    "Tampa, FL",
    "St. Petersburg, FL",
    "Clearwater, FL",
    "Brandon, FL",
    "Largo, FL",
    "Pinellas Park, FL",
    "Sarasota, FL",
    "Bradenton, FL",
    "Venice, FL",
    "Englewood, FL",
    "New Port Richey, FL",
    "Zephyrhills, FL",
    "Dade City, FL",
    "Brooksville, FL",
    "Spring Hill, FL",
    # Orlando / Central
    "Orlando, FL",
    "Kissimmee, FL",
    "Sanford, FL",
    "Apopka, FL",
    "Oviedo, FL",
    "Ocoee, FL",
    "Winter Garden, FL",
    "Altamonte Springs, FL",
    "Winter Springs, FL",
    "Casselberry, FL",
    "Longwood, FL",
    "Winter Park, FL",
    "Maitland, FL",
    "St. Cloud, FL",
    "Deltona, FL",
    "Daytona Beach, FL",
    "Ormond Beach, FL",
    "Port Orange, FL",
    "New Smyrna Beach, FL",
    "Edgewater, FL",
    "Titusville, FL",
    "Cocoa, FL",
    "Rockledge, FL",
    "Palm Bay, FL",
    "Melbourne, FL",
    "Lakeland, FL",
    "Winter Haven, FL",
    "Bartow, FL",
    "Clermont, FL",
    "Leesburg, FL",
    "The Villages, FL",
    "Inverness, FL",
    "Sebring, FL",
    "Avon Park, FL",
    # Treasure Coast
    "Port St. Lucie, FL",
    "Fort Pierce, FL",
    "Stuart, FL",
    "Jensen Beach, FL",
    "Palm City, FL",
    "Vero Beach, FL",
    "Sebastian, FL",
    "Palm Coast, FL",
    # Southwest / Gulf
    "Cape Coral, FL",
    "Fort Myers, FL",
    "Bonita Springs, FL",
    "Estero, FL",
    "Naples, FL",
    "Marco Island, FL",
    "Punta Gorda, FL",
    "Port Charlotte, FL",
    "North Port, FL",
    "Lehigh Acres, FL",
    "Sanibel, FL",
    # Southeast / Miami-Dade & Broward
    "Miami, FL",
    "Hialeah, FL",
    "Miami Gardens, FL",
    "Homestead, FL",
    "North Miami, FL",
    "Fort Lauderdale, FL",
    "Hollywood, FL",
    "Pembroke Pines, FL",
    "Miramar, FL",
    "Coral Springs, FL",
    "Pompano Beach, FL",
    "Davie, FL",
    "Sunrise, FL",
    "Plantation, FL",
    "Deerfield Beach, FL",
    "Tamarac, FL",
    "Coconut Creek, FL",
    "Margate, FL",
    "Cutler Bay, FL",
    "Hallandale Beach, FL",
    "North Lauderdale, FL",
    # Palm Beach County
    "West Palm Beach, FL",
    "Boca Raton, FL",
    "Delray Beach, FL",
    "Boynton Beach, FL",
    "Lake Worth Beach, FL",
    "Wellington, FL",
    "Jupiter, FL",
    "Greenacres, FL",
    "Royal Palm Beach, FL",
    "Palm Beach Gardens, FL",
    # Keys
    "Key West, FL",
    "Key Largo, FL",
    "Marathon, FL",
]
